import { Request, Response } from "express";
import Booking from "../models/booking";
import Restaurant from "../models/restaurant";

// ─── Controller: createBooking ────────────────────────────────────────────────
/**
 * @desc    Create a new table reservation for the authenticated customer
 * @route   POST /api/bookings
 * @access  Private (requires 'protect' middleware)
 *
 * Flow:
 *  1. Extract booking details from req.body and the authenticated user from req.user.
 *  2. Fetch the restaurant to get its totalSeats and verify it exists/is approved.
 *  3. *** CRITICAL: Slot Validation with .reduce() ***
 *       a. Query the database for all CONFIRMED bookings for the same
 *          restaurant, on the same date, at the same time slot.
 *       b. Use .reduce() to sum up the total guests already booked in that slot.
 *       c. Check: (alreadyBookedSeats + requestedGuests) <= totalSeats.
 *       d. If the slot is over capacity, return a 409 Conflict error.
 *  4. If capacity is available, create the new Booking document.
 *     The bookingId is auto-generated by the pre-save hook in the model.
 *  5. Populate the restaurant field and return the confirmed booking to the client.
 *
 * This is the most important business logic function in the app —
 * it prevents double-booking and overbooking at the database level.
 */
export const createBooking = async (req: Request, res: Response): Promise<void> => {
  try {
    const { restaurantId, date, time, guests, occasion, specialRequests } = req.body;
    const userId = req.user!._id; // Guaranteed by the 'protect' middleware

    // Step 1 Validation: Ensure all required fields are present
    if (!restaurantId || !date || !time || !guests) {
      res.status(400).json({
        success: false,
        message: "restaurantId, date, time, and guests are required fields.",
      });
      return;
    }

    // Step 2: Fetch the restaurant to validate existence, approval, and get capacity
    const restaurant = await Restaurant.findById(restaurantId);

    if (!restaurant) {
      res.status(404).json({ success: false, message: "Restaurant not found." });
      return;
    }

    if (restaurant.status !== "approved") {
      res.status(400).json({
        success: false,
        message: "This restaurant is not currently accepting reservations.",
      });
      return;
    }

    // Validate that the requested time slot is actually offered by this restaurant
    if (!restaurant.availableSlots.includes(time)) {
      res.status(400).json({
        success: false,
        message: `The time slot "${time}" is not available at this restaurant.`,
      });
      return;
    }

    // Step 3a: Build a date range for the target day to query bookings correctly.
    // We search between 00:00:00 and 23:59:59 of the requested date to catch
    // all bookings stored on that calendar day.
    const bookingDate = new Date(date);
    const startOfDay = new Date(bookingDate);
    startOfDay.setHours(0, 0, 0, 0);
    const endOfDay = new Date(bookingDate);
    endOfDay.setHours(23, 59, 59, 999);

    // Step 3a: Fetch all existing CONFIRMED bookings for this restaurant/date/time combination.
    // We only count 'confirmed' bookings — cancelled ones free up their seats.
    const existingBookings = await Booking.find({
      restaurant: restaurantId,
      date: { $gte: startOfDay, $lte: endOfDay },
      time: time,          // Exact time slot match
      status: "confirmed", // Only count active reservations
    });

    // Step 3b: *** THE .reduce() CAPACITY VALIDATION ***
    // .reduce() iterates over all existing bookings for this slot.
    // The accumulator (totalBookedSeats) starts at 0 and grows by
    // each booking's guest count, giving us the total seats in use.
    //
    // Interview Tip: This is O(n) where n = number of existing bookings
    // for that specific slot. With the compound index on (restaurant, date, time),
    // the MongoDB query itself is very efficient.
    const totalBookedSeats = existingBookings.reduce(
      (accumulator, booking) => accumulator + booking.guests,
      0 // Initial value: 0 seats booked
    );

    const requestedGuests = Number(guests);

    // Step 3c: Check if adding the requested guests would exceed total capacity
    if (totalBookedSeats + requestedGuests > restaurant.totalSeats) {
      const remainingSeats = restaurant.totalSeats - totalBookedSeats;
      res.status(409).json({
        success: false,
        message:
          remainingSeats <= 0
            ? `Sorry, the ${time} slot is fully booked for ${new Date(date).toDateString()}.`
            : `Not enough seats available. Only ${remainingSeats} seat(s) remaining in the ${time} slot.`,
      });
      return;
    }

    // Step 4: All validations passed — create the booking document.
    // The bookingId (e.g., "GR-71B448A7") is auto-generated by the pre-save hook.
    const newBooking = await Booking.create({
      user: userId,
      restaurant: restaurantId,
      date: bookingDate,
      time,
      guests: requestedGuests,
      occasion: occasion || "",
      specialRequests: specialRequests || "",
      status: "confirmed",
    });

    // Step 5: Populate the restaurant field so the frontend gets the full
    // restaurant details (name, location, address, image) in the response.
    // This matches the shape of dummyBookingData in the frontend assets.
    const populatedBooking = await Booking.findById(newBooking._id).populate(
      "restaurant",
      "name location address image slug cuisine" // Only select needed fields
    );

    res.status(201).json({
      success: true,
      message: "Reservation confirmed!",
      data: populatedBooking,
    });
  } catch (error: unknown) {
    const message =
      error instanceof Error ? error.message : "Failed to create booking.";
    res.status(500).json({ success: false, message });
  }
};

// ─── Controller: getMyBookings ────────────────────────────────────────────────
/**
 * @desc    Fetch all bookings (upcoming + history) for the logged-in customer
 * @route   GET /api/bookings/my
 * @access  Private (requires 'protect' middleware)
 *
 * Flow:
 *  1. Get the authenticated user's ID from req.user (set by 'protect' middleware).
 *  2. Query the database for all bookings where user === authenticated user's ID.
 *  3. Populate the restaurant field with selected details (name, slug, location,
 *     address, image, cuisine) — this matches the dummyMyBookingsData shape.
 *  4. Sort by date (newest first) and return.
 *
 * The frontend's Dashboard.tsx separates these into 'upcoming' and 'past'
 * on the client side, so we return ALL bookings and let the UI filter them.
 */
export const getMyBookings = async (req: Request, res: Response): Promise<void> => {
  try {
    // Step 1: The authenticated user's ID is attached to req.user by 'protect'
    const userId = req.user!._id;

    // Step 2 & 3: Find all bookings for this user and populate restaurant info
    const bookings = await Booking.find({ user: userId })
      .populate(
        "restaurant",
        "name slug location address image cuisine" // Fields needed by the Dashboard UI
      )
      .sort({ date: -1 }); // Newest bookings first

    res.status(200).json({
      success: true,
      count: bookings.length,
      data: bookings,
    });
  } catch (error: unknown) {
    const message =
      error instanceof Error ? error.message : "Failed to fetch your bookings.";
    res.status(500).json({ success: false, message });
  }
};

// ─── Controller: cancelBooking ────────────────────────────────────────────────
/**
 * @desc    Cancel a specific booking owned by the authenticated customer
 * @route   PATCH /api/bookings/:id/cancel
 * @access  Private (requires 'protect' middleware)
 *
 * Flow:
 *  1. Get the booking ID from URL params and the user ID from req.user.
 *  2. Find the booking by its _id AND verify it belongs to the current user.
 *     This is a critical security check — users must NOT be able to cancel
 *     other users' bookings.
 *  3. Check that the booking is still in 'confirmed' status (can't cancel
 *     something that's already cancelled or completed).
 *  4. Update the booking status to 'cancelled' and save.
 *  5. Return the updated booking document.
 */
export const cancelBooking = async (req: Request, res: Response): Promise<void> => {
  try {
    const { id } = req.params; // The booking's MongoDB _id
    const userId = req.user!._id;

    // Step 2: Find the booking AND verify ownership in one query.
    // If user is different, findOne returns null → 404 (no info leak).
    const booking = await Booking.findOne({ _id: id, user: userId });

    if (!booking) {
      res.status(404).json({
        success: false,
        message: "Booking not found or you are not authorized to cancel it.",
      });
      return;
    }

    // Step 3: Business rule — can only cancel 'confirmed' bookings
    if (booking.status !== "confirmed") {
      res.status(400).json({
        success: false,
        message: `This booking cannot be cancelled because its status is '${booking.status}'.`,
      });
      return;
    }

    // Step 4: Update status to 'cancelled'
    booking.status = "cancelled";
    await booking.save(); // Triggers the timestamps.updatedAt to be refreshed

    res.status(200).json({
      success: true,
      message: "Reservation cancelled successfully.",
      data: booking,
    });
  } catch (error: unknown) {
    const message =
      error instanceof Error ? error.message : "Failed to cancel booking.";
    res.status(500).json({ success: false, message });
  }
};

// ─── Controller: getBookingById ───────────────────────────────────────────────
/**
 * @desc    Get a single booking by its MongoDB _id (ownership-checked)
 * @route   GET /api/bookings/:id
 * @access  Private (requires 'protect' middleware)
 *
 * Flow:
 *  1. Find the booking by _id, ensuring it belongs to the current user.
 *  2. Populate restaurant details for display.
 *  3. Return the booking, or 404 if not found / not owned by this user.
 */
export const getBookingById = async (req: Request, res: Response): Promise<void> => {
  try {
    const { id } = req.params;
    const userId = req.user!._id;

    // The { user: userId } condition enforces ownership — security check
    const booking = await Booking.findOne({ _id: id, user: userId }).populate(
      "restaurant",
      "name slug location address image cuisine"
    );

    if (!booking) {
      res.status(404).json({
        success: false,
        message: "Booking not found.",
      });
      return;
    }

    res.status(200).json({ success: true, data: booking });
  } catch (error: unknown) {
    const message =
      error instanceof Error ? error.message : "Failed to fetch booking.";
    res.status(500).json({ success: false, message });
  }
};
